"""Interface models and contracts for permissions."""

from __future__ import annotations


DEFAULT_PERMISSION_DEFINITIONS: tuple[dict[str, str], ...] = (
    {"key": "user:read",            "resource": "user",           "action": "read",   "description": "View users"},
    {"key": "user:write",           "resource": "user",           "action": "write",  "description": "Invite, update, and approve users"},
    {"key": "role:read",            "resource": "role",           "action": "read",   "description": "View roles and permissions"},
    {"key": "role:write",           "resource": "role",           "action": "write",  "description": "Create and update roles"},
    {"key": "comment:read",         "resource": "comment",        "action": "read",   "description": "View comments"},
    {"key": "comment:write",        "resource": "comment",        "action": "write",  "description": "Create and update comments"},
    {"key": "entity_record:read",   "resource": "entity_record",  "action": "read",   "description": "View entity records"},
    {"key": "entity_record:write",  "resource": "entity_record",  "action": "write",  "description": "Create, update and delete entity records"},
    {"key": "workflow:read",        "resource": "workflow",       "action": "read",   "description": "View workflows"},
    {"key": "workflow:write",       "resource": "workflow",       "action": "write",  "description": "Create and update workflows"},
    {"key": "metadata:read",        "resource": "metadata",       "action": "read",   "description": "View metadata configuration"},
    {"key": "metadata:write",       "resource": "metadata",       "action": "write",  "description": "Update metadata configuration"},
    {"key": "integration:read",     "resource": "integration",    "action": "read",   "description": "View integrations"},
    {"key": "integration:write",    "resource": "integration",    "action": "write",  "description": "Create and update integrations"},
    {"key": "agent:read",           "resource": "agent",          "action": "read",   "description": "View agents"},
    {"key": "agent:write",          "resource": "agent",          "action": "write",  "description": "Create and update agents"},
    {"key": "form:read",            "resource": "form",           "action": "read",   "description": "View forms and form schemas"},
    {"key": "form:write",           "resource": "form",           "action": "write",  "description": "Create and update forms"},
    {"key": "field_library:read",   "resource": "field_library",  "action": "read",   "description": "View library fields and field types"},
    {"key": "field_library:write",  "resource": "field_library",  "action": "write",  "description": "Create, update, archive and delete library fields"},
    {"key": "method_library:read",  "resource": "method_library", "action": "read",   "description": "View methods and method categories"},
    {"key": "method_library:write", "resource": "method_library", "action": "write",  "description": "Create, update, delete and clone methods"},
    {"key": "file:read",            "resource": "file",           "action": "read",   "description": "View uploaded files"},
    {"key": "file:write",           "resource": "file",           "action": "write",  "description": "Upload and manage files"},
    {"key": "email_template:read",  "resource": "email_template", "action": "read",   "description": "View email templates"},
    {"key": "email_template:write", "resource": "email_template", "action": "write",  "description": "Create and update email templates"},
    {"key": "projection:read",      "resource": "projection",     "action": "read",   "description": "View pipeline projections, funnels, and heatmaps"},
    {"key": "projection:write",     "resource": "projection",     "action": "write",  "description": "Create and refresh pipeline projections and heatmaps"},
    {"key": "dashboard:read",       "resource": "dashboard",      "action": "read",   "description": "View the dashboard"},
    {"key": "dashboard:write",      "resource": "dashboard",      "action": "write",  "description": "Create and update the dashboard"},
    {"key": "analytics:read",       "resource": "analytics",      "action": "read",   "description": "View organization usage analytics"},
    {"key": "agent_trace:read",     "resource": "agent_trace",    "action": "read",   "description": "View agent run traces"},
    {"key": "logs:read",            "resource": "logs",           "action": "read",   "description": "View org-wide field change logs"},
    {"key": "api_coverage:read",    "resource": "api_coverage",   "action": "read",   "description": "View API coverage reports"},
    {"key": "settings:access",      "resource": "settings",       "action": "access", "description": "Access the settings section"},
    {"key": "connector:read",       "resource": "connector",      "action": "read",   "description": "View connectors"},
    {"key": "connector:write",      "resource": "connector",      "action": "write",  "description": "Create, update, and delete connectors"},
    {"key": "organization:branding",         "resource": "organization",         "action": "branding",  "description": "Update the caller's own organization's branding"},
    {"key": "organization:rename",           "resource": "organization",         "action": "rename",    "description": "Rename the caller's own organization"},
    {"key": "tool_execution:read",           "resource": "tool_execution",       "action": "read",      "description": "View tool execution audit logs for the caller's own organization"},
    {"key": "platform_organization:create",  "resource": "platform_organization","action": "create",    "description": "Create a new tenant organization"},
    {"key": "platform_organization:read",    "resource": "platform_organization","action": "read",      "description": "View any tenant organization"},
    {"key": "platform_organization:write",   "resource": "platform_organization","action": "write",     "description": "Update any tenant organization"},
    {"key": "platform_organization:approve", "resource": "platform_organization","action": "approve",   "description": "Approve a pending tenant organization"},
    {"key": "platform_organization:reject",  "resource": "platform_organization","action": "reject",    "description": "Reject a pending tenant organization"},
    {"key": "platform_organization:delete",  "resource": "platform_organization","action": "delete",    "description": "Delete any tenant organization"},
    {"key": "platform_organization:provision","resource": "platform_organization","action": "provision","description": "Provision tenant resources for any organization"},
    {"key": "platform_user:read",            "resource": "platform_user",        "action": "read",      "description": "View users of any tenant organization"},
    {"key": "platform_user:write",           "resource": "platform_user",        "action": "write",     "description": "Add, update, or remove users of any tenant organization"},
)
