import type { FieldType, FormField, FormSchema } from '../../../../core/types';

export function toFieldId(value: string): string {
  return value
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '_')
    .replace(/^_+|_+$/g, '');
}

export function normalizeEntityType(value: string): string {
  return value.trim();
}

const FIELD_ID_SUFFIX_START = 2;

export function generateFieldId(label: string, existingFields: FormField[], excludeIndex: number): string {
  const base = toFieldId(label) || 'field';
  let candidate = base;
  let counter = FIELD_ID_SUFFIX_START;
  while (existingFields.some((f, i) => f.id === candidate && (excludeIndex === -1 || i !== excludeIndex))) {
    candidate = `${base}_${counter++}`;
  }
  return candidate;
}

export const FIELD_TYPES: { value: FieldType; label: string }[] = [
  { value: 'text', label: 'Text' },
  { value: 'textarea', label: 'Text Area' },
  { value: 'email', label: 'Email' },
  { value: 'phone', label: 'Phone' },
  { value: 'integer', label: 'Integer' },
  { value: 'datetime', label: 'Date & Time' },
  { value: 'select', label: 'Select' },
  { value: 'multi_select', label: 'Multi Select' },
  { value: 'picklist_multi', label: 'Picklist Multi (Dropdown Add)' },
  { value: 'boolean', label: 'Checkbox' },
  { value: 'url', label: 'URL' },
  { value: 'currency', label: 'Currency' },
  { value: 'table', label: 'Table / Grid' },
  { value: 'auto_number', label: 'Auto Number' },
  { value: 'document', label: 'Document' },
  { value: 'timer_duration', label: 'Timer / Duration' },
];

export const FIELD_TYPE_LABELS: Record<FieldType, string> = {
  text: 'Text',
  textarea: 'Text Area',
  email: 'Email',
  phone: 'Phone',
  number: 'Number',
  integer: 'Integer',
  date: 'Date',
  datetime: 'Date & Time',
  select: 'Select',
  multi_select: 'Multi Select',
  picklist_multi: 'Picklist Multi (Dropdown Add)',
  boolean: 'Checkbox',
  url: 'URL',
  table: 'Table / Grid',
  auto_number: 'Auto Number',
  currency: 'Currency',
  section: 'Section',
  reference: 'Reference',
  document: 'Document',
  timer_duration: 'Timer / Duration',
};

/**
 * Field types that cannot be used as a picklist_multi extension field:
 * `section`, `picklist_multi`, `reference`, `auto_number`, `timer_duration`.
 *
 * `section` is a layout placeholder with no value; `picklist_multi` would nest a
 * wizard inside a wizard; `reference`, `auto_number` and `timer_duration` are
 * resolved or generated by the backend per record, which it can only do for a
 * top-level entity field, not for a value nested inside one.
 *
 * `document` IS supported — do not add it back here. `EntitiesServiceManager.
 * _validate_extension_document_values` walks each row's `extensions`, and
 * `_read_option_document_values` claims an option's files under the nested key
 * `<field>.<option>.<extension field id>`, so a file uploaded before the record
 * exists is handed to `_attach_unowned_document_files` like a top-level one.
 */
export const EXTENSION_DISALLOWED_TYPES: readonly FieldType[] = [
  'section',
  'picklist_multi',
  'reference',
  'auto_number',
  'timer_duration',
];

export const ENTITY_TYPE_LABELS: Record<string, string> = {
  Candidate: 'Candidate',
  Job: 'Job',
  Application: 'Application',
  Requisition: 'Requisition',
};

const DEFAULT_SECTION_FIELDS: Record<string, FormField[]> = {
  Application: [
    {
      id: 'comments',
      label: 'Comments',
      type: 'section',
      required: false,
      system: true,
      editable: false,
    },
  ],
};

export function injectMissingSectionFields(entityType: string, schemaFields: FormField[]): FormField[] {
  const defaultSections = DEFAULT_SECTION_FIELDS[normalizeEntityType(entityType)] || [];
  if (defaultSections.length === 0) return schemaFields;
  const missingSections = defaultSections.filter(
    (defaultField) => !schemaFields.some((f) => f.id === defaultField.id)
  );
  if (missingSections.length === 0) return schemaFields;
  return [...schemaFields, ...missingSections];
}

export function getSchemaFieldsForEntity(schemas: FormSchema[], entityType: string): FormField[] {
  const normalizedEntityType = normalizeEntityType(entityType);
  const schema = schemas.find(
    (s) => normalizeEntityType(s.entity_type) === normalizedEntityType && s.is_active
  );
  return schema?.schema?.fields?.filter((f) => f.type !== 'section' && f.type !== 'reference') || [];
}
