import type { StateMachineDocument } from "./types";

export const SAMPLE_MACHINE: StateMachineDocument = {
  machine_name: "ats_application_full_example",
  base_version: 1,
  definition: {
    machine_key: "ats_application_full_example",
    name: "ATS Application Full Example",
    description: "Full state machine example using all supported definition fields.",
    entity_type: "application",
    entity_schema: {
      entity_type: "application",
      fields: [
        {
          field: "candidate_name",
          type: "string",
          required: true,
          nullable: false,
          default: "Jane Candidate",
          enum_values: [],
          picklist_id: null,
          description: "Candidate full name.",
        },
        {
          field: "resume_url",
          type: "string",
          required: false,
          nullable: true,
          default: "https://example.com/resume.pdf",
          enum_values: [],
          picklist_id: null,
          description: "Resume document URL.",
        },
        {
          field: "screening_score",
          type: "int",
          required: false,
          nullable: true,
          default: 4,
          enum_values: [],
          picklist_id: null,
          description: "Recruiter screening score.",
        },
        {
          field: "interview_score",
          type: "float",
          required: false,
          nullable: true,
          default: 4.5,
          enum_values: [],
          picklist_id: null,
          description: "Interview feedback score.",
        },
        {
          field: "background_check_passed",
          type: "boolean",
          required: false,
          nullable: true,
          default: true,
          enum_values: [],
          picklist_id: null,
          description: "Whether background checks passed.",
        },
        {
          field: "applied_date",
          type: "datetime",
          required: false,
          nullable: true,
          default: "2026-04-27T00:00:00Z",
          enum_values: [],
          picklist_id: null,
          description: "Date the candidate applied.",
        },
        {
          field: "interview_start_at",
          type: "datetime",
          required: false,
          nullable: true,
          default: "2026-04-27T10:00:00Z",
          enum_values: [],
          picklist_id: null,
          description: "Interview start time.",
        },
        {
          field: "interview_end_at",
          type: "datetime",
          required: false,
          nullable: true,
          default: "2026-04-27T11:00:00Z",
          enum_values: [],
          picklist_id: null,
          description: "Interview end time.",
        },
        {
          field: "candidate_status",
          type: "enum",
          required: false,
          nullable: true,
          default: "active",
          enum_values: ["active", "offer_ready", "rejected", "hired"],
          picklist_id: null,
          description: "Candidate disposition.",
        },
        {
          field: "interview_feedback",
          type: "text",
          required: false,
          nullable: true,
          default: "Strong technical and communication signals.",
          enum_values: [],
          picklist_id: null,
          description: "Interview feedback notes.",
        },
        {
          field: "metadata",
          type: "json",
          required: false,
          nullable: true,
          default: { source: "linkedin", priority: "high" },
          enum_values: [],
          picklist_id: null,
          description: "Additional structured metadata.",
        },
        {
          field: "offer_amount",
          type: "float",
          required: false,
          nullable: true,
          default: 120000.0,
          enum_values: [],
          picklist_id: null,
          description: "Offer amount.",
        },
        {
          field: "rejection_reason",
          type: "text",
          required: false,
          nullable: true,
          default: "Role fit mismatch.",
          enum_values: [],
          picklist_id: null,
          description: "Reason for rejection.",
        },
      ],
    },
    states: [
      { name: "applied", description: "Application has been received.", tags: ["initial"], order: 1, sla_seconds: null },
      { name: "screening", description: "Recruiter screening is in progress.", tags: [], order: 2, sla_seconds: null },
      { name: "interview", description: "Candidate is in interview process.", tags: [], order: 3, sla_seconds: null },
      { name: "offer", description: "Offer is being prepared.", tags: [], order: 4, sla_seconds: null },
      { name: "hired", description: "Candidate has accepted and joined.", tags: ["terminal"], order: 5, sla_seconds: null },
      { name: "rejected", description: "Candidate has been rejected or withdrawn.", tags: ["terminal"], order: 6, sla_seconds: null },
    ],
    initial_state: "applied",
    transitions: [
      {
        key: "applied_to_screening",
        trigger: "start_screening",
        label: "Start Screening",
        from: "applied",
        to_state: "screening",
        required_fields: [{ field: "resume_url", required: true, type: "string" }],
        guards: [
          {
            type: "field_present",
            field: "resume_url",
            value: null,
            message: "Resume is required before screening.",
            config: {},
          },
          {
            type: "field_exact_match",
            field: "candidate_status",
            value: "active",
            message: "Only active candidates can enter screening.",
            config: {},
          },
        ],
        pre_transition_tasks: [
          {
            task: "validate_resume",
            label: "Validate Resume",
            order: 1,
            required: true,
            on_failure: "stop",
            config: { parser: "default" },
          },
        ],
        post_transition_tasks: [
          {
            task: "task_record_transition",
            label: "Record Transition",
            order: 1,
            required: true,
            on_failure: "stop",
            config: { audit: true },
          },
        ],
        auto_transition: { enabled: false, delay_seconds: 0 },
        description: "Move a new application into screening.",
      },
      {
        key: "screening_to_interview",
        trigger: "advance_to_interview",
        label: "Advance to Interview",
        from: "screening",
        to_state: "interview",
        required_fields: [{ field: "screening_score", required: true, type: "int" }],
        guards: [
          {
            type: "numerical_value_gte",
            field: "screening_score",
            value: 3,
            message: "Screening score must be at least 3.",
            config: {},
          },
        ],
        pre_transition_tasks: [],
        post_transition_tasks: [],
        auto_transition: { enabled: false },
        description: "Move a screened candidate to interview.",
      },
      {
        key: "interview_to_offer",
        trigger: "recommend_offer",
        label: "Recommend Offer",
        from: "interview",
        to_state: "offer",
        required_fields: [
          { field: "interview_feedback", required: true, type: "text" },
          { field: "interview_start_at", required: true, type: "datetime" },
          { field: "interview_end_at", required: true, type: "datetime" },
        ],
        guards: [
          {
            type: "compare_dates",
            field: "interview_start_at",
            value: null,
            message: "Interview start must be before interview end.",
            config: { other_field: "interview_end_at", operator: "lte" },
          },
        ],
        pre_transition_tasks: [],
        post_transition_tasks: [],
        auto_transition: { enabled: false },
        description: "Recommend candidate for offer.",
      },
      {
        key: "offer_to_hired",
        trigger: "mark_hired",
        label: "Mark Hired",
        from: "offer",
        to_state: "hired",
        required_fields: [
          { field: "offer_amount", required: true, type: "float" },
          { field: "background_check_passed", required: true, type: "boolean" },
        ],
        guards: [
          {
            type: "field_exact_match",
            field: "background_check_passed",
            value: true,
            message: "Background check must be passed.",
            config: {},
          },
        ],
        pre_transition_tasks: [],
        post_transition_tasks: [],
        auto_transition: { enabled: false },
        description: "Complete workflow as hired.",
      },
      {
        key: "screening_to_rejected",
        trigger: "reject_after_screening",
        label: "Reject After Screening",
        from: "screening",
        to_state: "rejected",
        required_fields: [{ field: "rejection_reason", required: true, type: "text" }],
        guards: [],
        pre_transition_tasks: [],
        post_transition_tasks: [],
        auto_transition: null,
        description: "Reject candidate from screening.",
      },
      {
        key: "interview_to_rejected",
        trigger: "reject_after_interview",
        label: "Reject After Interview",
        from: "interview",
        to_state: "rejected",
        required_fields: [{ field: "rejection_reason", required: true, type: "text" }],
        guards: [],
        pre_transition_tasks: [],
        post_transition_tasks: [],
        auto_transition: null,
        description: "Reject candidate after interview.",
      },
      {
        key: "offer_to_rejected",
        trigger: "decline_offer",
        label: "Decline Offer",
        from: "offer",
        to_state: "rejected",
        required_fields: [{ field: "rejection_reason", required: true, type: "text" }],
        guards: [],
        pre_transition_tasks: [],
        post_transition_tasks: [],
        auto_transition: null,
        description: "Close workflow when offer is declined.",
      },
    ],
  },
};

export function emptyMachine(): StateMachineDocument {
  return {
    machine_name: "new_state_machine",
    base_version: 1,
    definition: {
      machine_key: "new_state_machine",
      name: "New State Machine",
      description: "",
      entity_type: "entity",
      entity_schema: { entity_type: "entity", fields: [] },
      states: [
        { name: "draft", description: "Initial state.", tags: ["initial"], order: 1, sla_seconds: null },
      ],
      initial_state: "draft",
      transitions: [],
    },
  };
}
