server {
    listen 80;
    server_name myhub.62-238-103-67.sslip.io;
    location /.well-known/acme-challenge/ { root /var/www/certbot; }
    location / { return 301 https://myhub.62-238-103-67.sslip.io$request_uri; }
}
