import { useState, type FormEvent } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { hrCockpitApi } from "@/skins/hrms/api/hrCockpit";
import { apiErrorMessage as getApiErrorMessage } from "@/skins/hrms/lib/apiError";

const input = "w-full rounded-lg border border-gray-300 px-3 py-2 text-sm";
const button = "rounded-full bg-cobalt px-4 py-2 text-sm font-semibold text-white disabled:opacity-50";
type Tab = "policies"|"events"|"jobs"|"holidays";

export default function HrCockpitPage() {
  const qc = useQueryClient(); const [tab,setTab]=useState<Tab>("policies"); const [show,setShow]=useState(false); const [error,setError]=useState("");
  const [holidayYear,setHolidayYear]=useState(new Date().getFullYear());
  const {data,isLoading}=useQuery({queryKey:["hr-cockpit"],queryFn:hrCockpitApi.dashboard});
  const refresh=()=>qc.invalidateQueries({queryKey:["hr-cockpit"]});
  const action=useMutation({mutationFn:({kind,id,a}:{kind:string;id:string;a:string})=>hrCockpitApi.transition(kind,id,a),onSuccess:refresh,onError:e=>setError(getApiErrorMessage(e))});
  if(isLoading||!data) return <p>Loading HR cockpit…</p>;
  const recruiter=data.role==="Recruiter"; const holidayYears=Array.from(new Set([new Date().getFullYear()-1,new Date().getFullYear(),new Date().getFullYear()+1,...data.holidays.map(x=>Number(String(x.holiday_date).slice(0,4)))])).sort();
  const rows=tab==="policies"?data.policies:tab==="events"?data.events:tab==="holidays"?data.holidays.filter(x=>Number(String(x.holiday_date).slice(0,4))===holidayYear):data.openings;
  const addLabel=tab==="policies"?"policy":tab==="events"?"L&D event":tab==="jobs"?"job content":"holiday";
  return <div className="space-y-6"><div className="flex items-start justify-between"><div><h1 className="text-3xl font-semibold">HR cockpit</h1><p className="mt-1 text-gray-600">Draft, approve and publish employee content from one place.</p></div><button className={button} onClick={()=>setShow(!show)}>Add {addLabel}</button></div>
    <div className="flex gap-2">{([...(recruiter?[]:["policies","events"]),"jobs",...(recruiter?[]:["holidays"])] as Tab[]).map(x=><button key={x} onClick={()=>{setTab(x);setShow(false)}} className={`rounded-full px-4 py-2 text-sm ${tab===x?"bg-cobalt text-white":"border border-cobalt text-cobalt"}`}>{x==="events"?"L&D calendar":x[0].toUpperCase()+x.slice(1)}</button>)}</div>
    {tab==="holidays"&&<div className="flex items-center gap-3"><label htmlFor="holiday-year" className="text-sm font-medium text-gray-700">Holiday year</label><select id="holiday-year" className="rounded-lg border border-gray-300 bg-white px-4 py-2" value={holidayYear} onChange={e=>{setHolidayYear(Number(e.target.value));setShow(false)}}>{holidayYears.map(year=><option key={year} value={year}>{year}</option>)}</select><span className="text-sm text-gray-500">{rows.length} holiday{rows.length===1?"":"s"}</span></div>}
    {error&&<p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{show&&<CreateForm tab={tab} data={data} holidayYear={holidayYear} done={()=>{setShow(false);refresh()}} fail={setError}/>}
    {tab==="jobs"&&<JdPanel data={data} done={refresh} fail={setError}/>}
    <div className="overflow-hidden rounded-2xl border bg-white"><table className="w-full text-left text-sm"><thead className="bg-gray-50 text-gray-600"><tr><th className="p-4">Item</th><th>Status</th><th>Details</th><th className="p-4">Actions</th></tr></thead><tbody>{rows.map(x=><tr key={x.id} className="border-t"><td className="p-4 font-medium">{x.title||x.name||x.job_description?.title}</td><td><span className="rounded-full bg-blue-50 px-2 py-1 text-xs text-blue-700">{x.status.replaceAll("_"," ")}</span></td><td>{x.category||x.holiday_date||x.requisition_code}</td><td className="p-4 space-x-2">{x.status==="draft"&&<button className="text-cobalt" onClick={()=>action.mutate({kind:tab==="jobs"?"openings":tab,id:x.id,a:"submit"})}>Submit</button>}{x.status==="pending_approval"&&data.role!=="HR - Basic"&&<button className="text-cobalt" onClick={()=>action.mutate({kind:tab==="jobs"?"openings":tab,id:x.id,a:"approve"})}>Approve</button>}{tab==="jobs"&&x.status==="approved"&&<button className="text-cobalt" onClick={()=>action.mutate({kind:"openings",id:x.id,a:"publish"})}>Publish</button>}</td></tr>)}</tbody></table>{!rows.length&&<p className="p-8 text-center text-gray-500">No content yet. Add the first item.</p>}</div>
  </div>
}

function CreateForm({tab,data,holidayYear,done,fail}:{tab:Tab;data:any;holidayYear:number;done:()=>void;fail:(s:string)=>void}) { const [f,setF]=useState<Record<string,string>>({}); const set=(k:string)=>(e:any)=>setF({...f,[k]:e.target.value}); const submit=async(e:FormEvent)=>{e.preventDefault();if(tab==="holidays"&&Number(f.holiday_date?.slice(0,4))!==holidayYear){fail(`Choose a holiday date in ${holidayYear}.`);return}try{if(tab==="policies")await hrCockpitApi.createPolicy({...f,effective_date:f.effective_date});else if(tab==="events")await hrCockpitApi.createEvent({...f,starts_at:f.starts_at,ends_at:f.ends_at});else if(tab==="holidays")await hrCockpitApi.createHoliday({...f,is_optional:false});else await hrCockpitApi.createOpening({...f,openings:Number(f.openings||1)});done()}catch(e){fail(getApiErrorMessage(e))}};
  return <form onSubmit={submit} className="grid gap-3 rounded-2xl border bg-white p-5 md:grid-cols-2">{tab==="policies"&&<><input required className={input} placeholder="Policy title" onChange={set("title")}/><input required className={input} placeholder="Category" onChange={set("category")}/><input required type="date" className={input} onChange={set("effective_date")}/><input className={input} placeholder="Owner" onChange={set("owner")}/><textarea required className={input} placeholder="Summary" onChange={set("summary")}/><textarea required className={input} placeholder="Full policy" onChange={set("body")}/></>}{tab==="events"&&<><input required className={input} placeholder="Event title" onChange={set("title")}/><input required className={input} placeholder="Category" onChange={set("category")}/><input required type="datetime-local" className={input} onChange={set("starts_at")}/><input required type="datetime-local" className={input} onChange={set("ends_at")}/><input required className={input} placeholder="Location or meeting link" onChange={set("location")}/><input className={input} placeholder="Audience" onChange={set("audience")}/></>}{tab==="holidays"&&<><input required className={input} placeholder="Holiday name" onChange={set("name")}/><input required type="date" className={input} onChange={set("holiday_date")}/><input className={input} placeholder="Location" onChange={set("location")}/><input className={input} placeholder="Description" onChange={set("description")}/></>}{tab==="jobs"&&<><select required className={input} onChange={set("job_description_id")}><option value="">Job description</option>{data.job_descriptions.map((x:any)=><option value={x.id}>{x.title}</option>)}</select><input required className={input} placeholder="Requisition code" onChange={set("requisition_code")}/><select required className={input} onChange={set("hiring_manager_id")}><option value="">Hiring manager</option>{data.hiring_managers.map((x:any)=><option value={x.id}>{x.name}</option>)}</select><input className={input} type="number" placeholder="Openings" onChange={set("openings")}/><input required className={input} placeholder="Location" onChange={set("location")}/><input required className={input} placeholder="Work mode" onChange={set("work_mode")}/><input required type="date" className={input} onChange={set("application_deadline")}/></>}<button className={button}>Save draft</button></form> }

function JdPanel({data,done,fail}:{data:any;done:()=>void;fail:(s:string)=>void}) { const [open,setOpen]=useState(false),[f,setF]=useState<Record<string,string>>({}); const set=(k:string)=>(e:any)=>setF({...f,[k]:e.target.value}); return <div className="rounded-2xl border bg-white p-5"><div className="flex justify-between"><div><h2 className="font-semibold">Job description library</h2><p className="text-sm text-gray-500">{data.job_descriptions.length} reusable JDs</p></div><button className="text-sm font-semibold text-cobalt" onClick={()=>setOpen(!open)}>Add JD</button></div>{open&&<form className="mt-4 grid gap-3 md:grid-cols-2" onSubmit={async e=>{e.preventDefault();try{await hrCockpitApi.createJd(f);setOpen(false);done()}catch(e){fail(getApiErrorMessage(e))}}}><input required className={input} placeholder="Role title" onChange={set("title")}/><input required className={input} placeholder="Department" onChange={set("department")}/><input required className={input} placeholder="Level" onChange={set("level")}/><input className={input} placeholder="Experience" onChange={set("experience")}/><textarea required className={input} placeholder="Responsibilities" onChange={set("responsibilities")}/><textarea required className={input} placeholder="Requirements" onChange={set("requirements")}/><button className={button}>Save JD</button></form>}</div> }
