"""The only runtime adapter to the platform: public HTTP contracts, no core imports."""
from __future__ import annotations

import threading
import time
from dataclasses import dataclass

import httpx

from .errors import AppError


@dataclass(frozen=True)
class Actor:
    user_id: str
    organization_id: str
    token: str
    roles: frozenset[str]
    permissions: frozenset[str]
    project_policy: dict | None = None
    cockpit_policy: dict | None = None


class PlatformClient:
    def __init__(self, url: str, organization_id: str, email: str, password: str,
                 *, transport=None):
        self.org = organization_id
        self.email = email
        self.password = password
        self.http = httpx.Client(base_url=url.rstrip('/') + '/', timeout=30,
                                 follow_redirects=False, transport=transport)
        self._token = ''
        self._expires = 0.0
        self._login_lock = threading.Lock()

    def close(self):
        self.http.close()

    def request(self, method: str, path: str, *, token: str = '', **kwargs):
        # Paths are generated by this adapter; never accept an upstream URL from callers.
        if not path.startswith('/') or path.startswith('//') or '..' in path:
            raise ValueError('Invalid platform API path')
        headers = {'Authorization': f'Bearer {token}'} if token else {}
        try:
            response = self.http.request(method, path.lstrip('/'), headers=headers, **kwargs)
        except httpx.RequestError as exc:
            raise AppError(503, 'The platform is unavailable; retry using the same operation key') from exc
        if response.status_code >= 400:
            if response.status_code >= 500:
                raise AppError(502, 'The platform could not complete this operation')
            try:
                detail = response.json().get('detail', 'Platform request was rejected')
            except ValueError:
                detail = 'Platform request was rejected'
            raise AppError(response.status_code, str(detail))
        if response.status_code == 204:
            return None
        return response.json()

    def service_token(self):
        with self._login_lock:
            if time.monotonic() >= self._expires:
                data = self.request('POST', '/auth/login', json={
                    'email': self.email, 'password': self.password})
                token = data['access_token']
                permissions = self.request('GET', '/roles/my-permissions', token=token)
                if permissions.get('organization_id') != self.org:
                    raise AppError(503, 'HRMS service identity belongs to another organization')
                self._token = token
                self._expires = time.monotonic() + 240
            return self._token

    def call(self, method, path, **kwargs):
        # A platform restart or token expiry can invalidate a cached service session.
        # Keep service authentication failures separate from the browser session.
        for attempt in range(2):
            token = ''
            try:
                token = self.service_token()
                return self.request(method, path, token=token, **kwargs)
            except AppError as exc:
                if exc.status != 401:
                    raise
                with self._login_lock:
                    if self._token == token:
                        self._expires = 0.0
                if attempt:
                    raise AppError(503, 'HRMS could not authenticate to the platform; please retry shortly') from exc

    def actor(self, token: str) -> Actor:
        user = self.request('GET', '/auth/me', token=token)
        permissions = self.request('GET', '/roles/my-permissions', token=token)
        org = permissions.get('organization_id')
        memberships = self.request('GET', '/users/me/organizations', token=token)
        active = any(m['organization_id'] == org and m['status'] == 'active'
                     and m['organization_status'] == 'active'
                     for m in memberships['organizations'])
        if org != self.org or user.get('status') != 'active' or not active:
            raise AppError(403, 'An active membership in this HRMS organization is required')
        if permissions.get('user_id') != user['id']:
            raise AppError(403, 'The session identity does not match its permissions')
        return Actor(user['id'], org, token,
                     frozenset(r['name'] for r in permissions['roles']),
                     frozenset(permissions['permissions']))

    def records(self, entity_type: str, fields: list[str]) -> list[dict]:
        """Use the platform cursor API; never silently truncate an aggregation."""
        result, cursor = [], None
        while True:
            params = {'entity_type_name': entity_type, 'fields': ','.join(fields), 'limit': 200}
            if cursor:
                params['cursor'] = cursor
            page = self.call('GET', '/entity-records/summary', params=params)
            for row in page['items']:
                if row['organization_id'] != self.org:
                    raise AppError(502, 'Platform returned data outside the configured organization')
                result.append({**row, 'data': row['summary_fields']})
            if not page['has_more']:
                return result
            next_cursor = page.get('next_cursor')
            if not next_cursor or next_cursor == cursor:
                raise AppError(502, 'Platform returned an incomplete entity page')
            cursor = next_cursor

    def record(self, entity_id):
        row = self.call('GET', f'/entity-records/{entity_id}')
        if row['organization_id'] != self.org:
            raise AppError(404, 'Record was not found')
        return row

    def users(self):
        result, offset = [], 0
        while True:
            rows = self.call('GET', '/users', params={'limit': 200, 'offset': offset})
            result.extend(rows)
            if len(rows) < 200:
                return result
            offset += 200

    def states(self, machine):
        machine = self.machine_name(machine)
        result, offset = {}, 0
        while True:
            page = self.call('GET', '/workflow-enrollments', params={
                'machine_name': machine, 'limit': 200, 'offset': offset})
            for row in page['items']:
                result[row['entity_id']] = row['current_state']
            if page.get('scan_truncated'):
                raise AppError(502, 'Platform workflow result was truncated')
            if not page['has_more']:
                return result
            offset += len(page['items'])
            if not page['items']:
                raise AppError(502, 'Platform returned an incomplete workflow page')

    def steps_by_case(self):
        rows = self.records('HRMS.OnboardingStep', ['case_id', 'sequence', 'title',
            'description', 'assigned_to', 'due_date', 'legacy_task_id'])
        states = self.states('hrms_onboardingstep')
        grouped = {}
        for row in rows:
            grouped.setdefault(row['data'].get('case_id'), []).append(dict(id=row['entity_id'], stage=f"onboarding-step-{row['data']['sequence']}",
                     title=row['data']['title'], description=row['data'].get('description'),
                     assigned_to=row['data'].get('assigned_to'), due_date=row['data'].get('due_date'),
                     status=states.get(row['entity_id'], 'not_started').upper()))
        return grouped

    def tasks(self, entity_id):
        return self.steps_by_case().get(entity_id, [])

    def create_record(self, entity_type, data, owner_id):
        type_row = self.call('GET', f'/entity-types/{entity_type}')
        return self.call('POST', '/entity-records', json={
            'organization_id': self.org, 'entity_type_id': type_row['entity_type_id'],
            'data': data, 'owner_id': owner_id})

    def enroll(self, entity_id, machine):
        machine = self.machine_name(machine)
        state = self.states(machine).get(entity_id)
        if state:
            return state
        return self.call('POST', f'/workflow-state-machines/{machine}/enrollments',
                         json={'entity_id': entity_id})['current_state']

    def machine_name(self, name):
        from .catalog import PACKS
        pack = next((p for p in PACKS if p.machine_name == name), None)
        if not pack:
            return name
        workflows = self.call('GET', '/workflow-state-machines', params={'scope': 'published'})['published_items']
        matches = [w for w in workflows if w['entity_type'] == pack.entity_type and w['is_active']]
        if len(matches) != 1:
            raise AppError(409, f'{pack.label} needs exactly one active workflow')
        return matches[0]['machine_name']
