import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { CheckCircle2, Plus, Star, Target, Users } from "lucide-react";
import { useState } from "react";

import { performanceApi, type PerformanceCycle, type PerformanceGoal, type PerformanceReview, type ProjectFeedback } from "@/skins/hrms/api/performance";
import { Badge } from "@/skins/hrms/components/Badge";
import { Button } from "@/skins/hrms/components/Button";
import { Card, CardHeader, CardTitle } from "@/skins/hrms/components/Card";
import { Field, FormError, Select, TextArea, TextInput } from "@/skins/hrms/components/Form";
import { Modal } from "@/skins/hrms/components/Modal";
import { apiErrorMessage } from "@/skins/hrms/lib/apiError";

type Tab = "mine" | "team" | "feedback" | "cycles";
type FormAction = { kind: "self" | "manager" | "calibrate"; review: PerformanceReview } | { kind: "feedback"; feedback: ProjectFeedback } | null;

const today = () => new Date().toLocaleDateString("en-CA");
const addMonths = (months: number) => { const value = new Date(); value.setMonth(value.getMonth() + months); return value.toLocaleDateString("en-CA"); };
const ratingText = (rating?: number | null) => rating ? `${rating} · ${["", "Needs improvement", "Partially meets", "Meets expectations", "Exceeds expectations", "Exceptional"][rating]}` : "Not rated";

export default function PerformancePage() {
  const queryClient = useQueryClient();
  const [tab, setTab] = useState<Tab>("mine");
  const [cycleEdit, setCycleEdit] = useState<PerformanceCycle | "new" | null>(null);
  const [goalEdit, setGoalEdit] = useState<{review: PerformanceReview; goal?: PerformanceGoal} | null>(null);
  const [formAction, setFormAction] = useState<FormAction>(null);
  const [comment, setComment] = useState("");
  const dashboard = useQuery({ queryKey: ["performance-dashboard"], queryFn: performanceApi.dashboard });
  const refresh = async () => queryClient.invalidateQueries({ queryKey: ["performance-dashboard"] });
  const act = useMutation({ mutationFn: async ({fn}: {fn: () => Promise<unknown>}) => fn(), onSuccess: async () => { setComment(""); await refresh(); } });
  const data = dashboard.data;

  return <div className="space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-light tracking-tight text-gray-900">Performance management</h1><p className="mt-1 text-sm text-gray-600">Set goals, complete reviews, collect project feedback, and publish calibrated outcomes.</p></div>{data?.can_manage_cycles && <Button onClick={() => setCycleEdit("new")}><Plus size={16}/> New cycle</Button>}</div>
    <div className="grid gap-3 sm:grid-cols-3"><Card><div className="flex items-center gap-3"><Target className="text-cobalt"/><div><strong className="text-xl">{data?.my_reviews.length ?? 0}</strong><p className="text-sm text-gray-600">My review cycles</p></div></div></Card><Card><div className="flex items-center gap-3"><Users className="text-cobalt"/><div><strong className="text-xl">{data?.team_reviews.filter(r => ["submitted_to_manager","manager_submitted"].includes(r.status)).length ?? 0}</strong><p className="text-sm text-gray-600">Team actions</p></div></div></Card><Card><div className="flex items-center gap-3"><Star className="text-cobalt"/><div><strong className="text-xl">{data?.feedback_requests.filter(f => f.status === "pending").length ?? 0}</strong><p className="text-sm text-gray-600">Feedback requests</p></div></div></Card></div>
    <div className="flex flex-wrap gap-2" role="tablist"><Button variant={tab === "mine" ? "primary" : "secondary"} onClick={() => setTab("mine")}>My performance</Button>{!!data?.team_reviews.length && <Button variant={tab === "team" ? "primary" : "secondary"} onClick={() => setTab("team")}>Team reviews</Button>}{!!data?.feedback_requests.length && <Button variant={tab === "feedback" ? "primary" : "secondary"} onClick={() => setTab("feedback")}>Project feedback</Button>}{data?.can_manage_cycles && <Button variant={tab === "cycles" ? "primary" : "secondary"} onClick={() => setTab("cycles")}>Review cycles</Button>}</div>
    {dashboard.isLoading ? <p className="text-sm text-gray-600">Loading performance workspace…</p> : dashboard.error ? <FormError message={apiErrorMessage(dashboard.error)}/> : <>
      {tab === "mine" && <div className="space-y-4">{!data?.my_reviews.length && <Card><p className="text-sm text-gray-600">No active performance cycle has been assigned to you.</p></Card>}{data?.my_reviews.map(review => <ReviewCard key={review.id} review={review} mine onAddGoal={() => setGoalEdit({review})} onEditGoal={goal => setGoalEdit({review,goal})} onAction={setFormAction} act={fn => act.mutate({fn})} comment={comment} setComment={setComment}/>)}</div>}
      {tab === "team" && <div className="space-y-4">{data?.team_reviews.map(review => <ReviewCard key={review.id} review={review} onAction={setFormAction} act={fn => act.mutate({fn})} comment={comment} setComment={setComment} canPublish={!!data.can_manage_cycles}/>)}</div>}
      {tab === "feedback" && <div className="grid gap-4 md:grid-cols-2">{data?.feedback_requests.map(item => <Card key={item.id}><div className="flex justify-between gap-2"><div><CardTitle>{item.employee_name}</CardTitle><p className="text-sm text-gray-600">{item.project_name}</p></div><Badge>{item.status}</Badge></div>{item.status === "pending" ? <Button className="mt-4" onClick={() => setFormAction({kind:"feedback",feedback:item})}>Provide feedback</Button> : <p className="mt-3 text-sm">{ratingText(item.rating)} · {item.contribution}</p>}</Card>)}</div>}
      {tab === "cycles" && <CycleList cycles={data?.cycles ?? []} canApprove={!!data?.can_approve_cycles} edit={setCycleEdit} act={fn => act.mutate({fn})} comment={comment} setComment={setComment}/>}</>}
    <FormError message={act.error ? apiErrorMessage(act.error) : null}/>
    {cycleEdit && <CycleModal cycle={cycleEdit === "new" ? undefined : cycleEdit} close={() => setCycleEdit(null)} refresh={refresh}/>} {goalEdit && <GoalModal review={goalEdit.review} goal={goalEdit.goal} close={() => setGoalEdit(null)} refresh={refresh}/>} {formAction && <ReviewActionModal action={formAction} close={() => setFormAction(null)} refresh={refresh}/>}
  </div>;
}

function ReviewCard({review,mine=false,onAddGoal,onEditGoal,onAction,act,comment,setComment,canPublish=false}:{review:PerformanceReview;mine?:boolean;onAddGoal?:()=>void;onEditGoal?:(goal:PerformanceGoal)=>void;onAction:(value:FormAction)=>void;act:(fn:()=>Promise<unknown>)=>void;comment:string;setComment:(v:string)=>void;canPublish?:boolean}) {
  const total = review.goals.reduce((sum,g)=>sum+g.weight,0); const goalsPending = review.goals.some(g=>g.status==="pending_approval"); const goalsApproved = review.goals.length>0 && review.goals.every(g=>g.status==="approved") && total===100;
  return <Card><CardHeader><div><CardTitle>{mine ? review.cycle.name : review.employee_name}</CardTitle><p className="text-sm text-gray-600">{mine ? `Manager: ${review.manager_name}` : review.cycle.name}</p></div><Badge>{review.status}</Badge></CardHeader>
    <div className="mb-4 grid gap-2 text-sm sm:grid-cols-3"><div><span className="text-gray-600">Goals due</span><p>{review.cycle.goal_due_date}</p></div><div><span className="text-gray-600">Self-review due</span><p>{review.cycle.self_review_due_date}</p></div><div><span className="text-gray-600">Manager due</span><p>{review.cycle.manager_review_due_date}</p></div></div>
    <div className="space-y-2">{review.goals.map(goal=><div key={goal.id} className="rounded-xl border border-gray-200 p-3"><div className="flex justify-between gap-2"><strong>{goal.title}</strong><div className="flex gap-2"><Badge>{goal.status}</Badge><span className="text-sm font-medium">{goal.weight}%</span></div></div><p className="mt-1 text-sm text-gray-600">{goal.category} · {goal.measurement}</p>{goal.manager_comment&&<p className="mt-1 text-sm text-danger">Manager: {goal.manager_comment}</p>}{mine&&["draft","changes_requested"].includes(goal.status)&&<Button className="mt-2" variant="ghost" onClick={()=>onEditGoal?.(goal)}>Edit goal</Button>}</div>)}</div>
    {review.self_summary && <div className="mt-4 rounded-xl bg-gray-50 p-3"><strong>Self-review · {ratingText(review.self_rating)}</strong><p className="mt-1 text-sm">{review.self_summary}</p></div>}
    {review.manager_summary && <div className="mt-3 rounded-xl bg-gray-50 p-3"><strong>Manager review · {ratingText(review.manager_rating)}</strong><p className="mt-1 text-sm">{review.manager_summary}</p></div>}
    {!mine && review.project_feedback.length > 0 && <div className="mt-3 rounded-xl border border-gray-200 p-3"><strong>Project feedback</strong>{review.project_feedback.map(item=><div key={item.id} className="mt-2 text-sm"><p className="font-medium">{item.project_name} · {item.status === "submitted" ? ratingText(item.rating) : "Awaiting feedback"}</p>{item.contribution&&<p className="text-gray-600">{item.contribution}</p>}</div>)}</div>}
    {review.final_rating && <div className="mt-3 rounded-xl border border-success/30 bg-success/5 p-3"><strong>Final rating · {ratingText(review.final_rating)}</strong>{review.calibration_comment&&<p className="mt-1 text-sm">{review.calibration_comment}</p>}</div>}
    <div className="mt-4 flex flex-wrap gap-2">{mine && ["not_started","self_draft"].includes(review.status) && <Button variant="secondary" onClick={onAddGoal}><Plus size={15}/> Add goal</Button>}{mine && review.goals.length>0 && total===100 && review.goals.every(g=>["draft","changes_requested"].includes(g.status)) && <Button onClick={()=>act(()=>performanceApi.submitGoals(review.id))}>Submit goals</Button>}{!mine && goalsPending && <><Button onClick={()=>act(()=>performanceApi.decideGoals(review.id,"approve",comment))}>Approve goals</Button><TextInput className="!w-64" placeholder="Reason for changes" value={comment} onChange={e=>setComment(e.target.value)}/><Button variant="danger" disabled={!comment.trim()} onClick={()=>act(()=>performanceApi.decideGoals(review.id,"changes_requested",comment))}>Request changes</Button></>}{mine && goalsApproved && ["not_started","self_draft"].includes(review.status) && <Button onClick={()=>onAction({kind:"self",review})}>Complete self-review</Button>}{!mine && review.status==="submitted_to_manager" && <Button onClick={()=>onAction({kind:"manager",review})}>Complete manager review</Button>}{!mine && review.status==="manager_submitted" && <Button onClick={()=>onAction({kind:"calibrate",review})}>Calibrate rating</Button>}{canPublish && review.status==="calibrated" && <Button onClick={()=>act(()=>performanceApi.publish(review.id))}>Publish result</Button>}{mine && review.status==="published" && <Button onClick={()=>act(()=>performanceApi.acknowledge(review.id))}><CheckCircle2 size={15}/> Acknowledge</Button>}</div>
    <p className="mt-3 text-xs text-gray-600">Goal weight: {total}%</p>
  </Card>;
}

function CycleList({cycles,canApprove,edit,act,comment,setComment}:{cycles:PerformanceCycle[];canApprove:boolean;edit:(cycle:PerformanceCycle)=>void;act:(fn:()=>Promise<unknown>)=>void;comment:string;setComment:(v:string)=>void}) { return <div className="space-y-4">{cycles.map(cycle=><Card key={cycle.id}><div className="flex flex-wrap justify-between gap-3"><div><CardTitle>{cycle.name}</CardTitle><p className="text-sm text-gray-600">{cycle.start_date} to {cycle.end_date} · Created by {cycle.created_by_name}</p></div><Badge>{cycle.status}</Badge></div>{cycle.description&&<p className="mt-3 text-sm">{cycle.description}</p>}<div className="mt-3 flex flex-wrap gap-2">{cycle.status==="draft"&&<><Button variant="secondary" onClick={()=>edit(cycle)}>Edit draft</Button><Button onClick={()=>act(()=>performanceApi.submitCycle(cycle.id))}>Submit for Super Admin approval</Button></>}{canApprove&&cycle.status==="pending_approval"&&<><Button onClick={()=>act(()=>performanceApi.decideCycle(cycle.id,"approve"))}>Approve and open</Button><TextInput className="!w-64" placeholder="Reason for changes" value={comment} onChange={e=>setComment(e.target.value)}/><Button variant="danger" disabled={!comment.trim()} onClick={()=>act(()=>performanceApi.decideCycle(cycle.id,"changes_requested",comment))}>Request changes</Button></>}</div></Card>)}</div>; }

function CycleModal({cycle,close,refresh}:{cycle?:PerformanceCycle;close:()=>void;refresh:()=>Promise<unknown>}) { const [form,setForm]=useState({name:cycle?.name??"",description:cycle?.description??"",start_date:cycle?.start_date??today(),end_date:cycle?.end_date??addMonths(12),goal_due_date:cycle?.goal_due_date??addMonths(1),self_review_due_date:cycle?.self_review_due_date??addMonths(10),manager_review_due_date:cycle?.manager_review_due_date??addMonths(11)}); const mutation=useMutation({mutationFn:()=>cycle?performanceApi.updateCycle(cycle.id,form):performanceApi.createCycle(form),onSuccess:async()=>{await refresh();close();}}); return <Modal open onClose={close} title={cycle?"Edit performance cycle":"Create performance cycle"}><form className="space-y-3" onSubmit={e=>{e.preventDefault();mutation.mutate();}}><Field label="Cycle name"><TextInput required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></Field><Field label="Description"><TextArea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></Field><div className="grid grid-cols-2 gap-3"><Field label="Start"><TextInput type="date" required value={form.start_date} onChange={e=>setForm({...form,start_date:e.target.value})}/></Field><Field label="End"><TextInput type="date" required value={form.end_date} onChange={e=>setForm({...form,end_date:e.target.value})}/></Field><Field label="Goals due"><TextInput type="date" required value={form.goal_due_date} onChange={e=>setForm({...form,goal_due_date:e.target.value})}/></Field><Field label="Self-review due"><TextInput type="date" required value={form.self_review_due_date} onChange={e=>setForm({...form,self_review_due_date:e.target.value})}/></Field><Field label="Manager review due"><TextInput type="date" required value={form.manager_review_due_date} onChange={e=>setForm({...form,manager_review_due_date:e.target.value})}/></Field></div><FormError message={mutation.error?apiErrorMessage(mutation.error):null}/><div className="flex justify-end gap-2"><Button type="button" variant="ghost" onClick={close}>Cancel</Button><Button type="submit" disabled={mutation.isPending}>{cycle?"Save changes":"Create draft"}</Button></div></form></Modal>; }

function GoalModal({review,goal,close,refresh}:{review:PerformanceReview;goal?:PerformanceGoal;close:()=>void;refresh:()=>Promise<unknown>}) { const [form,setForm]=useState({title:goal?.title??"",description:goal?.description??"",category:goal?.category??"delivery",measurement:goal?.measurement??"",weight:goal?.weight??Math.max(1,100-review.goals.reduce((s,g)=>s+g.weight,0)),target_date:goal?.target_date??review.cycle.end_date,progress:goal?.progress??0,evidence:goal?.evidence??""}); const mutation=useMutation({mutationFn:()=>goal?performanceApi.updateGoal(goal.id,form):performanceApi.createGoal(review.id,form),onSuccess:async()=>{await refresh();close();}}); return <Modal open onClose={close} title={goal?"Edit performance goal":"Add performance goal"}><form className="space-y-3" onSubmit={e=>{e.preventDefault();mutation.mutate();}}><Field label="Goal"><TextInput required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></Field><Field label="Category"><Select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{["delivery","competency","leadership","learning","organization"].map(v=><option key={v} value={v}>{v}</option>)}</Select></Field><Field label="Success measure"><TextArea required value={form.measurement} onChange={e=>setForm({...form,measurement:e.target.value})}/></Field><div className="grid grid-cols-2 gap-3"><Field label="Weight %"><TextInput type="number" min={1} max={100} value={form.weight} onChange={e=>setForm({...form,weight:Number(e.target.value)})}/></Field><Field label="Target date"><TextInput type="date" value={form.target_date} onChange={e=>setForm({...form,target_date:e.target.value})}/></Field></div><FormError message={mutation.error?apiErrorMessage(mutation.error):null}/><div className="flex justify-end gap-2"><Button type="button" variant="ghost" onClick={close}>Cancel</Button><Button type="submit">{goal?"Save goal":"Add goal"}</Button></div></form></Modal>; }

function ReviewActionModal({action,close,refresh}:{action:NonNullable<FormAction>;close:()=>void;refresh:()=>Promise<unknown>}) { const [rating,setRating]=useState(3); const [summary,setSummary]=useState(""); const mutation=useMutation({mutationFn:()=>action.kind==="feedback"?performanceApi.feedback(action.feedback.id,rating,summary):action.kind==="self"?performanceApi.selfReview(action.review.id,summary,rating):action.kind==="manager"?performanceApi.managerReview(action.review.id,summary,rating):performanceApi.calibrate(action.review.id,rating,summary),onSuccess:async()=>{await refresh();close();}}); const title=action.kind==="feedback"?`Feedback for ${action.feedback.employee_name}`:action.kind==="self"?"Complete self-review":action.kind==="manager"?`Review ${action.review.employee_name}`:`Calibrate ${action.review.employee_name}`; return <Modal open onClose={close} title={title}><form className="space-y-3" onSubmit={e=>{e.preventDefault();mutation.mutate();}}><Field label="Rating"><Select value={rating} onChange={e=>setRating(Number(e.target.value))}>{[1,2,3,4,5].map(v=><option key={v} value={v}>{ratingText(v)}</option>)}</Select></Field><Field label={action.kind==="feedback"?"Contribution feedback":"Summary and rationale"}><TextArea required rows={6} value={summary} onChange={e=>setSummary(e.target.value)}/></Field><FormError message={mutation.error?apiErrorMessage(mutation.error):null}/><div className="flex justify-end gap-2"><Button type="button" variant="ghost" onClick={close}>Cancel</Button><Button type="submit" disabled={mutation.isPending}>Submit</Button></div></form></Modal>; }
